name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version you want to release
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    name: Publish a new release
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with:
          version: ${{ github.event.inputs.version }}

      # In order to make a commit, we need to initialize a user.
      # You may choose to write something less generic here if you want, it doesn't matter functionality wise.
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Commit changelog
        id: make-commit
        run: |
          curl -fsSL https://dprint.dev/install.sh | sh
          /home/runner/.dprint/bin/dprint -c .github/workflows/.dprintrc.json fmt CHANGELOG.md
          git add CHANGELOG.md
          git commit --message "Release ${{ github.event.inputs.version }}"
          echo "LAST_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Push changelog modifications to master
        run: git push origin master

      - name: Create Release
        uses: thomaseizinger/create-release@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: ${{ env.LAST_COMMIT }}
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
