name: Static analysis

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  changelog:
    name: Changelog checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Changelog checker
        uses: dangoslen/changelog-enforcer@v3
        with:
          expectedLatestVersion: ''

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga:1.8.0
        env:
          REQUIRE_DEV: true
        with:
          args: analyze --no-progress

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '8.0'
          extensions: curl, json
          tools: composer:v2

      - name: Install latest dependencies
        run: composer update --ansi --no-interaction --no-progress --prefer-dist

      - name: PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --show-progress=none
