name: Static analysis

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  changelog:
    name: Changelog checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Changelog checker
        uses: dangoslen/changelog-enforcer@v2
        with:
          expectedLatestVersion: ''

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga:1.8.0
        env:
          REQUIRE_DEV: true
        with:
          args: analyze --no-progress

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga:3.26.0
        with:
          args: --dry-run --diff

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl
          tools: composer:v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: |
          composer require --dev --no-update psalm/phar:5.25.0
          composer update --no-interaction --prefer-dist

      - name: Psalm
        run: |
          ./vendor/bin/psalm.phar --version
          ./vendor/bin/psalm.phar --output-format=github --no-progress --show-info=false --stats
