name: Static analysis

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  changelog:
    name: Changelog checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Changelog checker
        uses: dangoslen/changelog-enforcer@v3
        with:
          expectedLatestVersion: ''

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga:1.8.0
        env:
          REQUIRE_DEV: true
        with:
          args: analyze --no-progress

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga:3.26.0
        with:
          args: --dry-run --diff

  psalm:
    name: Psalm
    runs-on: ubuntu-24.04
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl
          tools: composer:v2

      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install latest dependencies
        run: composer update --ansi --no-interaction --no-progress --prefer-dist

      - name: Download Psalm
        run: curl -sSL -o psalm.phar https://github.com/vimeo/psalm/releases/download/6.19.2/psalm.phar

      - name: Psalm
        run: |
          php psalm.phar --version
          php psalm.phar --output-format=github --no-progress --show-info=false --stats
